### ISSUE TITLE
Backend response to get error

### ISSUE THREAD

**Issue by ktrzos** [pqina/filepond#229]
What do I need to return in backend response to inform Filepond about error which was caused by one of uploaded files? I can't find any information about specific template in docs. What structure should be adapted to returned json?

**Comment by rikschennink** [comment]
I just checked the docs and indeed this might need some additional explanation.

It works like this:

If everything is fine, your server responds with an http status between 200 and 300

If something is wrong it responds with a status between 400 and 500

**Comment by ktrzos** [comment]
@rikschennink 
Thanks for your response!
I have another question. Lets say, that I'm uploading 3 files. One is uploaded correctly, one is too big, and the last one has invalid MIME type. It is possible to display proper error message near proper file?

**Comment by rikschennink** [comment]
Yes, you can of course validate this on the client using the validation plugins. Validation again on the server is wise.

You can return the matching 4xx status code, and then if necessary parse the response (you could return a custom response message or code).

To customize the message for each different error you can set `labelFileProcessingError` to a function and return a label based on the server error received.

```js
labelFileProcessingError: function(serverError) { return 'my error message'; } 
```

**Comment by ktrzos** [comment]
@rikschennink 

Thank you again! :)
I'll close this issue, and will open it again when I will have some more problems.

**Comment by ktrzos** [comment]
@rikschennink 

I implemented my backend to return 400 code with json in body with structure like this (when error occurs):

```
[
  "status": "error",
  "message": "custom message"
]
```

How to get value from "message"?
While using below code, the `response` variable does not contain my custom message. The `body` within this variable is a string with "Bad Request" value.

```
labelFileProcessingError={(response) => {
    console.log(response);
}
```

Structure of the `response` variable:

```
{
  "type": "error",
  "code": 400,
  "body": "Bad Request",
  "headers": "...."
}
```

**Comment by rikschennink** [comment]
You can use the `onerror` callback on the `server.process` object to filter the server response.

**Comment by Herz3h** [comment]
Was wondering the same about what should the server return in case of error. I think it's still not documented on the docs.

**Comment by rikschennink** [comment]
4**

**Comment by Herz3h** [comment]
I know from read your [previous comment](https://github.com/pqina/filepond/issues/229#issuecomment-463096902), my point is that it's probably better to just put in the docs, maybe in the server page ?

**Comment by rikschennink** [comment]
Aha. The docs are on GH, feel free to submit a PR
https://github.com/pqina/filepond-docs

**Comment by riliwanrabo** [comment]
```
const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create(inputElement);
        pond.setOptions({
            server: {
                process: {
                    url: '/upload',
                    onerror: (response) => {
                        console.log(response)
                    }
                },
                revert: '/upload/revert',
                headers: {
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': '{{ @csrf_token() }}'
                }
            }
        });
```
This works

**Comment by xlcrr** [comment]
This works for me 

```
<FilePond
    name="photo"
    :server="server"
    :labelFileProcessingError="options.labelFileProcessingError"
/>
            
const server = {

        onerror: (response) => {
            try {
                const errorResponse = JSON.parse(response);

                const errorMessage = errorResponse.error || 'An unknown error occurred.';

                // Pass the error message to filepond
                return errorMessage;

            } catch (e) {
                console.error('Error parsing response:', e);

                return 'An unknown error occurred. Please contact support';
            }
        },
};

const options = {
    // FilePond label to display when an upload fails
    labelFileProcessingError: (error) => {
        // Your error should now be set in this error response body
        return error.body;
    },
};
            
```
