### ISSUE TITLE
Preserve EXIF data?

### ISSUE THREAD

**Issue by lukey78** [pqina/filepond#250]
Hi,

it seems if I process the uploaded images with some plugins (crop, resize) the EXIF data on the uploaded image gets lost. Maybe that's also the case with uploading without plugins, but I didn't test that.

Is there any way to preserve it so that I can process the original image's EXIF data on the server?

Thank you!
Jens

**Comment by kimlambiguit** [comment]
setting imageTransformOutputStripImageHead to false still strips exif data. i'm trying to retrieve the exif data on the sever.process function. when i tested, i removed the FilePondPluginImageTransform plugin then printed out the exif data, with no problems, but when i added the plugin, setting the imageTransformOutputStripImageHead to false, nothing was retrieved.

**Comment by rikschennink** [comment]
@kimlambiguit Fixed in version `3.3.3`

**Comment by kimlambiguit** [comment]
thanks

**Comment by fisketavlingnu** [comment]
I still have problems with this. I'm using default source from unpkg.com
EXIF data is not kept. This is the settings I use:
![image](https://user-images.githubusercontent.com/53155624/71256073-0f47fd80-2330-11ea-9dd6-0ac626fd30a2.png)

**Comment by rikschennink** [comment]
@fisketavlingnu Please create a concise test case on codesandbox.io

**Comment by lukey78** [comment]
I can confirm that this happens again since version 3.4.0. See the linked issue.

**Comment by rikschennink** [comment]
@lukey78 @fisketavlingnu looking into it.

**Comment by rikschennink** [comment]
@lukey78 @fisketavlingnu Fixed in version `3.6.2`
