### ISSUE TITLE
Upload files queue broke while remove a file before is uploaded

### ISSUE THREAD

**Issue by ericforgues** [pqina/filepond#310]
Hi there!
First thing first, awesome plugin!

But sadly i found an issue, when we get a files queue and cancel one the file before his upload start, or if his upload fail, the next file to be uploaded never start.

I think the easiest way to reproduce this issue it's to upload something like 5 files on a filepond with maxParallelUploads to 1 (the bug exist also without this, but it more easy to test it like this).

While the first files upload, remove one of the waiting ones (else than the last one) and the upload queue will stop when it arrive to his "ghost".

Hope the description is enough to help you to reproduce the issue and fix it!

Thanks!

**Comment by rikschennink** [comment]
Should be fixed in version `4.4.3`

**Comment by tobias7an** [comment]
This problem still exists in version 4.4.11 when cancelling an active upload with multiple concurrent uploads. If there are 2 concurrent uploads, cancelling one will only "block" that upload "slot", the other upload slot still begins uploading the next file in line when it finishes, while cancelling both will leave all pending uploads in the "waiting" stage.

**Comment by rikschennink** [comment]
@tobias7an will run some tests

**Comment by rikschennink** [comment]
@tobias7an I can't reproduce this, do you have a custom `server.process` implementation, and if so, are you calling the `abort` method?

![Kapture 2019-07-18 at 9 51 27](https://user-images.githubusercontent.com/1132575/61439353-ad7b0600-a941-11e9-89aa-8998429066be.gif)
