### ISSUE TITLE
Order of input elements in FilePond subtree doesn't match order of files

### ISSUE THREAD

**Issue by hason** [pqina/filepond#465]
### Summary

Drag and drop only change position of files via css. DOM is unchanged. The hidden inputs doesn't reflect ordered positions of files. On server, the array of file names is not ordered.

### Expected behaviour

Drag and drop should move real DOM elements.

| Environment  | Version
|------------- | -----------
| OS           | Linux
| Device       | 
| Browser      | Chromium 80

**Comment by rikschennink** [comment]
Fixing now 👍

**Comment by rikschennink** [comment]
Should be fixed in v4.13.0

**Comment by hason** [comment]
@rikschennink Thanks!

**Comment by cloydlau** [comment]
Why can I still reproduce this in v4.13.0? I am using vue-filepond of which filepond is a peer dependency. Or is there a callback I can use to reorder files array manually?

**Comment by rikschennink** [comment]
@cloydlau I don't know why. Please supply a test case on codesandbox.

**Comment by cloydlau** [comment]
@rikschennink https://codesandbox.io/s/holy-night-told4?file=/src/App.vue

**Comment by rikschennink** [comment]
@cloydlau This is a FilePond vue specific issue, please create a new one there. The internal hidden input fields are reordered, the issue here is that the `files` prop is not being updated.

**Comment by cloydlau** [comment]
https://codesandbox.io/s/holy-night-told4
Already changed the dependency to filepond only. It seems files prop still can't be reordered.

**Comment by rikschennink** [comment]
@cloydlau that's because its value doesn't update. It's only used to send information to FilePond.

**Comment by cloydlau** [comment]
I need to refresh files value when order changed. I just found 'reorderfiles' event at #445 which will solve my problem perfectly, thanks. It's missing in document by the way.

**Comment by cloydlau** [comment]
Document says 'allowReorder' only works in single column mode. Actually it also works on grid layout with a little limit, the position that file items can be dropped onto is restricted in grid layout. Hope this could be optimized later on.
