### ISSUE TITLE
Order of hidden input fields incorrect (multiple occasions)

### ISSUE THREAD

**Issue by vjanssens** [pqina/filepond#505]
**Describe the bug**
The order of the hidden input fields in .filepond—data does not reflect the order that was given when initializing filepond for existing images.

I've followed the details as described [here](https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files).

I pass an array of images as shown below. The prefix _1 and _2 is in the correct order:
![afbeelding](https://user-images.githubusercontent.com/2340997/82678384-cfbc6f00-9c49-11ea-85f1-cd27b2807e6f.png)

When the files are loaded, the UI shows the images in the correct order. Unfortunately, the order of the hidden input fields is incorrect:

![afbeelding](https://user-images.githubusercontent.com/2340997/82678182-72282280-9c49-11ea-996e-51cf076d209c.png)

Notice _2 and _1 are in the wrong order.

**To Reproduce**
I've tried to reproduce the issue with a codesandbox, but did not know how to setup the server configuration to point to externally hosted images (as demo). Below demo is incomplete.

https://codesandbox.io/s/vanilla-filepond-0dsxz

**Expected behavior**
I expect the order of hidden input elements in the DOM to reflect the order as given when initialization and how the images are visible in the UI.

**Information about your project:**
- Latest Chrome and Firefox
- Latest MacOS
- Latest FilePond (4.13.7)

**Comment by vjanssens** [comment]
I'm not sure if it's related, but i'm getting similar out of order results when **uploading** multiple files at a time. The UI shows the images in the correct order, but `filepond--data` is in the exact opposite order (3, 2, 1, instead of 1, 2, 3).

**Comment by rikschennink** [comment]
I've confirmed the issue, will look into this as soon as possible. 👍

**Comment by rikschennink** [comment]
Should be fixed in 4.17.0
https://github.com/pqina/filepond/releases/tag/4.17.0

**Comment by vjanssens** [comment]
Hi Rik, thanks for looking into this but 4.17.1 does not seem to completely resolve the issue. The UI shows the images in the right order as I've set them in the `files: []` array, but the `.filepond--data` DOM element gets populated reversed. This is only when initializing Filepond. After I reorder 1 item, the rest of the hidden input fields in `.filepond--data` are set in the right order.

**Comment by rikschennink** [comment]
@vjanssens alright, will retest next week.

**Comment by rikschennink** [comment]
I've confirmed the issue, it should be fixed in `4.18.0` 👍

**Comment by mrkazmierczak** [comment]
This bug still exist in VUE I've set allow-reorder="true" and v-on:updatefiles="handleFilePondUpdate" in the component and array is not changing when I'm reordeing. 

```
methods: {
handleFilePondUpdate(files) 
{
    this.files = files.map(files => files.file);
    console.log(this.files);
}, 
}
```
